admin:
  categories:
    per_page: 10
  films:
    per_page: 20
  reviews:
    per_page: 20
  users:
    perpage: 20
  comments:
    perpage: 10
films:
  per_page: 10
  spotlight_limit: 4
  related_limit: 3
  trailer_limit: 5
email_from: "awesome.academy.test@gmail.com"
user:
  name:
    length:
      minimum: 3
  email:
    length:
      maximum: 50
  password:
    length:
      minimum: 6
comment:
  content:
    length:
      minimum: 10
